name: Running Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Load WEB_CLIENT_ID
        env:
          DATA: ${{ secrets.WEB_CLIENT_ID}}
        run: echo $DATA | base64 -di > common-domain/src/main/java/ke/don/shared_domain/values/Secrets.kt

      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebug